server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    properties:
      topic:
        start-saga: start-saga
        orchestrator: orchestrator
        finish-success: finish-success
        finish-fail: finish-fail
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest
         
  data:
    mongodb:
      database: admin
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:order-db}

logging:
  level:
    org:
      apache:
        kafka: OFF