version: "3"

services:
  order-db:
    image: mongo:4.4
    container_name: order-db
    restart: always
    networks:
      - orchestrator-saga
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"

  product-db:
    image: postgres:latest
    container_name: product-db
    networks:
      - orchestrator-saga
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  payment-db:
    image: postgres:latest
    container_name: payment-db
    networks:
      - orchestrator-saga
    environment:
      POSTGRES_DB: payment-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  inventory-db:
    image: postgres:latest
    container_name: inventory-db
    networks:
      - orchestrator-saga
    environment:
      POSTGRES_DB: inventory-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - orchestrator-saga
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - orchestrator-saga
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - kafka

  order-service:
    container_name: order-service
    build: ./order-service
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_HOST=order-db
      - MONGO_PORT=27017
      - MONGO_DB=order-db
    ports:
      - "3000:3000"
    depends_on:
      - order-db
      - kafka

  orchestrator-service:
    container_name: orchestrator-service
    build: ./orchestrator-service
    networks:
      - orchestrator-saga
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092

  product-validation-service:
    container_name: product-validation-service
    build: ./product-validation-service
    networks:
      - orchestrator-saga
    ports:
      - "8090:8090"
    depends_on:
      - product-db
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB-NAME=product-db
      - DB-HOST=product-db
      - DB-PORT=5432
      - DB-USER=postgres
      - DB-PASSWORD=postgres

  payment-service:
    container_name: payment-service
    build: ./payment-service
    networks:
      - orchestrator-saga
    ports:
      - "8091:8091"
    depends_on:
      - payment-db
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB-HOST=payment-db
      - DB-NAME=payment-db
      - DB-PORT=5432
      - DB-USER=postgres
      - DB-PASSWORD=postgres

  inventory-service:
    container_name: inventory-service
    build: ./inventory-service
    networks:
      - orchestrator-saga
    ports:
      - "8092:8092"
    depends_on:
      - inventory-db
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB-HOST=inventory-db
      - DB-NAME=inventory-db
      - DB-PORT=5432
      - DB-USER=postgres
      - DB-PASSWORD=postgres

networks:
  orchestrator-saga:
    driver: bridge
