server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: order-group
      auto-offset-reset: latest
    properties:
      topic.start-saga: start-saga
      topic.notify-ending: notify-ending
  
  data:
    mongodb:
      database: ${MONGO_DB:order-db}
      uri: mongodb://${MONGO_HOST:order-db}:${MONGO_PORT:27017}/${MONGO_DB:order-db}

logging:
  level:
    org:
      apache:
        kafka: OFF
