server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: order-group
      auto-offset-reset: latest
    properties:
      topic:
        start-saga: start-saga
        notify-ending: notify-ending

  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://root:root@localhost:27017}

logging:
  level:
    org:
      apache:
        kafka: OFF
